# Data Manipulation and Visualisation


## Learning objectives

dplyr

- Describe the purpose of the dplyr and tidyr packages.
- Select certain columns in a data frame with the dplyr function select.
- Select certain rows in a data frame according to filtering conditions with the dplyr function filter .
- Link the output of one dplyr function to the input of another function with the ‘pipe’ operator %>%.
- Add new columns to a data frame that are functions of existing columns with mutate.
- Use the split-apply-combine concept for data analysis.
- Use summarize, group_by, and count to split a data frame into groups of observations, apply a summary statistics for each group, and then combine the results.
- Describe the concept of a wide and a long table format and for which purpose those formats are useful.
- Describe what key-value pairs are.
- Reshape a data frame from long to wide format and back with the spread and gather commands from the tidyr package.
- Export a data frame to a .csv file.

ggplot2

- Produce scatter plots, boxplots, and time series plots using ggplot.
- Set universal plot settings.
- Describe what faceting is and apply faceting in ggplot.
- Modify the aesthetics of an existing ggplot plot (including axis labels and color).
- Build complex and customized plots from data in a data frame.

## Data manipulation with dplyr

- select()
- filter()
- mutate()
- arrange()
- tally()/count()
- group_by()
- summarise()

## Data visualisation with ggplot2

- ggplot()
- aes()
- geom_point()
- geom_line()
- facet_wrap()
- theme()
