# Databases and API's

This lesson is going to focus on how to programatically retrieve (genomic) data from online repositorys such as Ensembl, UCSC, and, BioMart

## Learning objectives

### SQL

- Explain the difference between a table, a record, and a field.
- Explain the difference between a database and a database manager.
- Write a query to select all values for specific fields from a single table.
- Write queries that display results in a particular order.
- Write queries that eliminate duplicate values from data.
- Write queries that select records that satisfy user-specified conditions.
- Explain the order in which the clauses in a query are executed.
- Write queries that calculate new values for each selected record.
- Explain how databases represent missing information.
- Explain the three-valued logic databases use when manipulating missing information.
- Write queries that handle missing information correctly.
- Define aggregation and give examples of its use.
- Write queries that compute aggregated values.
- Trace the execution of a query that performs aggregation.
- Explain how missing data is handled during aggregation.
- Explain the operation of a query that joins two tables.
- Explain how to restrict the output of a query containing a join to only include meaningful combinations of values.
- Write queries that join tables on equal keys.
- Explain what primary and foreign keys are, and why they are useful.
- Explain what an atomic value is.
- Distinguish between atomic and non-atomic values.
- Explain why every value in a database should be atomic.
- Explain what a primary key is and why every record should have one.
- Identify primary keys in database tables.
- Explain why database entries should not contain redundant information.
- Identify redundant information in databases.
- Write statements that create tables.
- Write statements to insert, modify, and delete records.
- Write short programs that execute SQL queries.
- Trace the execution of a program that contains an SQL query.
- Explain why most database applications are written in a general-purpose language rather than in SQL.


## SQL


### dplyr/dbplyr



### Refs

[Software Carpentry SQL lesson](https://swcarpentry.github.io/sql-novice-survey/)

## API's

### REST

Ref https://www.smashingmagazine.com/2018/01/understanding-using-rest-api/

#### BioMart

https://asia.ensembl.org/info/data/biomart/biomart_restful.html

#### Ensembl

https://github.com/Ensembl/ensembl-rest/wiki

#### UCSC

http://genomewiki.ucsc.edu/index.php/Programmatic_access_to_the_Genome_Browser